name: Approval Tracking

on:
  issues:
    types: [edited]

permissions:
  issues: write
jobs:
  check_checkbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2 

      - name: Check if checkbox was edited
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "User: ${{ github.event.issue.user.login }}"
          
          # Extract previous issue body from the webhook event
          PREVIOUS_BODY="${{ github.event.changes.body.from }}"
          echo "Previous Body: $PREVIOUS_BODY"
          
          # Extract currently checked checkboxes
          CURRENT_CHECKED=$(echo "${{ github.event.issue.body }}" | grep -E '\- \[x\]')
          
          USERNAME="${{ github.event.issue.user.login }}"
          NEW_CHECKED_ITEMS=""
          UPDATED_BODY="${{ github.event.issue.body }}"

          # Loop through the current checked items
          while IFS= read -r item; do
            item_name="${item#- }"  # Remove the leading "- "

            # Check if this item is newly checked
            if [[ "$item" =~ \[x\] ]] && ! grep -q "\- \[x\] $item_name" <<< "$PREVIOUS_BODY"; then
              echo "Debug: $item"
              # Replace the item in UPDATED_BODY with the checked status and username
              UPDATED_BODY="${UPDATED_BODY/\$item/- [x] $item_name (Checked by: $USERNAME)}"
            fi
          done <<< "$CURRENT_CHECKED"

          # If there are changes, update the issue body
          if [[ "$UPDATED_BODY" != "${{ github.event.issue.body }}" ]]; then
            echo "Updating the issue body..."
            echo "Body: $UPDATED_BODY"
            echo "$UPDATED_BODY" | gh issue edit ${{ github.event.issue.number }} --body -
          fi
