name: Approval Tracking

on:
  issue_comment:
    types: [created]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approval comment
        if: contains(github.event.comment.body, '/approve')
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          APPROVER=${{ github.actor }}

          # Add approval label based on the approver
          if [[ "$APPROVER" == "product-owner-username" ]]; then
            LABEL="Product Owner Approved"
          elif [[ "$APPROVER" == "developer-username" ]]; then
            LABEL="Developer Approved"
          elif [[ "$APPROVER" == "qa-username" ]]; then
            LABEL="QA Approved"
          fi

          # Add the appropriate label
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
            -d "{\"labels\":[\"$LABEL\"]}"
