name: Update Issue Checkbox

on:
  issues:
    types: [edited]

jobs:
  update-checkbox:
    runs-on: ubuntu-latest
    steps:
      - name: Check which checkbox was checked
        id: check_checkbox
        run: |
          CHECKBOX_CHECKED=false
          CHECKBOX_NAME=""
          OLD_BODY="${{ github.event.changes.body.from }}"
          NEW_BODY="${{ github.event.issue.body }}"
          
          if [[ "$OLD_BODY" != "$NEW_BODY" ]]; then
            if [[ "$OLD_BODY" =~ "- \[ \] BA" && "$NEW_BODY" =~ "- \[x\] BA" ]]; then
              CHECKBOX_CHECKED=true
              CHECKBOX_NAME="BA"
            elif [[ "$OLD_BODY" =~ "- \[ \] UX" && "$NEW_BODY" =~ "- \[x\] UX" ]]; then
              CHECKBOX_CHECKED=true
              CHECKBOX_NAME="UX"
            elif [[ "$OLD_BODY" =~ "- \[ \] DEV" && "$NEW_BODY" =~ "- \[x\] DEV" ]]; then
              CHECKBOX_CHECKED=true
              CHECKBOX_NAME="DEV"
            fi
          fi
          
          echo "CHECKBOX_CHECKED=$CHECKBOX_CHECKED" >> $GITHUB_ENV
          echo "CHECKBOX_NAME=$CHECKBOX_NAME" >> $GITHUB_ENV

      - name: Update issue with username
        if: env.CHECKBOX_CHECKED == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const username = context.actor;
            const checkboxName = process.env.CHECKBOX_NAME;
            const updatedBody = issueBody.replace(`- [x] ${checkboxName}`, `- [x] ${checkboxName} (@${username})`);
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: updatedBody
            });
