name: Approval Tracking

on:
  issues:
    types: [edited]

permissions:
  issues: write
jobs:
  check_checkbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2 

      - name: Check if checkbox was edited
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "User: ${{ github.event.issue.user.login }}"
          
          # Extract previous issue body from the webhook event
          PREVIOUS_BODY="${{ github.event.changes.body.from }}"
          echo "Previous Body: $PREVIOUS_BODY"
          
          # Extract currently checked checkboxes
          CURRENT_CHECKED=$(echo "${{ github.event.issue.body }}" | grep -E '\- \[x\]')
          
          USERNAME="${{ github.event.issue.user.login }}"
          NEW_CHECKED_ITEMS=""
          UPDATED_BODY="${{ github.event.issue.body }}"

          while IFS= read -r item; do
              item_name="${item#- }"  # Remove the leading "- "
              
              # Check if this item was previously unchecked
              if [[ "$item" =~ \[x\] ]] && ! grep -q "\- \[x\] $item_name" <<< "$PREVIOUS_BODY"; then
                  # Update the original body to reflect the newly checked item
                  echo "Debug: $item"
                  UPDATED_BODY="${UPDATED_BODY//$item/- [x] $item_name (Checked by: $USERNAME)}"
              fi
          done <<< "$CURRENT_CHECKED"

          # If there are changes, update the issue body
          if [[ "$UPDATED_BODY" != "${{ github.event.issue.body }}" ]]; then
              echo "Updating the issue body..."
              echo "Body: $UPDATED_BODY"
              gh issue edit ${{ github.event.issue.number }} --body "$UPDATED_BODY"
          fi
