name: Update Issue Checkbox

on:
  issues:
    types: [ edited ]

permissions:
  issues: write

jobs:
  update-checkbox:
    runs-on: ubuntu-latest
    steps:
      - name: new check
        uses: actions/github-script@v6
        with:
          script: |
            const checkboxes = ["BA", "UX", "DEV"];
            console.log(context.payload.issue.body)
            const issueBody= context.payload.issue.body
            const oldIssueBody = context.payload.changes.body.from
            if(issueBody.includes("- [x] BA") && oldIssueBody.includes("- [ ] BA")){
              console.log("BA is checked")
              const username = context.actor;
              const updatedBody = issueBody.replace(`- [x] BA`, `- [x] BA (@${username})`);
              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: updatedBody
              });
            }

      - name: Check which checkbox was checked
        if: false
        id: check_checkbox
        run: |
          CHECKBOXES=("BA" "UX")
          
          CHECKBOX_CHECKED=false
          CHECKBOX_NAME=""
          OLD_BODY="${{ github.event.changes.body.from }}"
          NEW_BODY="${{ github.event.issue.body }}"

          for CHECKBOX_TEXT in "${CHECKBOXES[@]}"; do
            if echo "$NEW_BODY" | grep -q "\- [x] $CHECKBOX_TEXT"; then
              echo "Checkbox '$CHECKBOX_TEXT' is already checked."
              continue
            fi
          done
          
          if [[ "$OLD_BODY" != "$NEW_BODY" ]]; then
            echo "old != new"
            if [[ "$OLD_BODY" =~ "- \\[ \\] BA" ]]; then
              echo "BA was unchecked"
            fi
            if [[ "$NEW_BODY" =~ "- \\[x\\] BA" ]]; then
              echo "BA is checked"
              CHECKBOX_CHECKED=true
              CHECKBOX_NAME="BA"
            fi
          fi
          
          echo "CHECKBOX_CHECKED=$CHECKBOX_CHECKED" >> $GITHUB_ENV
          echo "CHECKBOX_NAME=$CHECKBOX_NAME" >> $GITHUB_ENV

      - name: Update issue with username
        if: env.CHECKBOX_CHECKED == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const username = context.actor;
            const checkboxName = process.env.CHECKBOX_NAME;
            const updatedBody = issueBody.replace(`- [x] ${checkboxName}`, `- [x] ${checkboxName} (@${username})`);
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: updatedBody
            });
